### ISSUE TITLE
2324-W-002 IPAA batch upload to Wikidata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#10]
2324-W-002
https://docs.google.com/document/d/1iWYY2NwBrHUPQ44IaOKmme9wssm5NLkLQaaojC9pyQI/edit
```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-planet-ipaa/issues/6
- [ ] https://github.com/culturecreates/artsdata-planet-ipaa/issues/1
- [x] Switch approach of creating URIs for IPAA members to UUIDs
- [x] document switch to UUIDs in Nebula report
- [ ] https://github.com/culturecreates/artsdata-orion/issues/23
- [ ] https://github.com/culturecreates/artsdata-orion/issues/21
- [ ] https://github.com/culturecreates/artsdata-orion/issues/22
- [ ] https://github.com/culturecreates/artsdata-orion/issues/20
- [x] Compare the 2022 individual artists dataset to the 2023 individual artists dataset. Do this using "member of [Indigenous Performing Arts Alliance](https://www.wikidata.org/wiki/Q110938829)” and check point in time. If individual artists are missing in 2023, this may mean they no longer are members. If that’s the case, provide a list to CAPACOA.
- [x] Add "lastest start date" to artists
```

**Comment by saumier** [comment]
Report 
https://docs.google.com/document/d/1OmgeM4eM6b6fkp3Z9PhFGwBQcABmPGhTJaT2W1HA9zs/edit

**Comment by saumier** [comment]
https://editgroups.toolforge.org/b/OR/a6b8bc91f74/

**Comment by saumier** [comment]
Orgs https://editgroups.toolforge.org/b/OR/1e0bb490fae/

**Comment by saumier** [comment]
[Adding IPAA Membership to entities already existing in Wikidata](https://editgroups.toolforge.org/b/OR/4a559cb3106/)

**Comment by saumier** [comment]
Adding latest start date to all artists that had a "point in time".
