### ISSUE TITLE
ETL Evenko

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#103]
https://evenko.ca/en/feeds/venue/place-bell
The feed includes several non-performance events. We should exclude from the ETL events where "is_sports": true.

For the imageObject we should add:
copyrightNotice: @en ''© Copyright source: evenko 2024. All rights reserved.'' 
copyrightNotice: @fr ''© Copyright source: evenko 2024. Tous droits réservés.''

```[tasklist]
### Tasks
- [x] Create a new repo called artsdata-planet-evenko
- [x] Create transformation of image URL into ImageObject
- [x] ETL to Artsdata using OntoRefine
```

**Comment by saumier** [comment]
Here a reference ImageObject to consider. See if you can add any of the other properties.

```
{
  "@type": "ImageObject",
  "url": "--URL officiel de l'image : Official image URL--",
  "copyrightNotice": "--licence et attribution au propriétaire du droit d'auteur : license and attribution to the copyright owner--",
  "usageInfo": "--lien vers les directives concernant la réutilisation des images d'événements : link to suggested guidelines for reusing event images--",
  "author": {
       "@type": "Person",
      "name": "--Nom du photographe ou créateur d'image : Name of photographer or image creator--"
                     },
  "disambiguatingDescription": "--description sous forme de formule, telle que « Image de NOM DE L'ÉVÉNEMENT, provenant de NOM DE DOMAINE DU SITE WEB » : formulaic description, such as 'Image of EVENT NAME, sourced from WEBSITE DOMAIN NAME'--",
  "creditText": "--credit photo complet, y compris le nom du photographe, de la compagnie de production et des interprètes représentés sur la scène : full photo credit, including the name of the photographer, production company and performers represented onstage --",
  "caption": "--explication d'une ligne de ce que l'image représente : one-line explanation of what the image represents--",
  "description": "--Alt texte, si disponible : Alt text, if available--"
}
```

**Comment by dev-aravind** [comment]
@saumier Just to make sure, the venue for all the places should be Place Bell right?

**Comment by saumier** [comment]
@dev-aravind Yes.

**Comment by dev-aravind** [comment]
@saumier The first pass is now complete and you can test it [here](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20evenko-ca&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-evenko/evenko-ca).

**Comment by saumier** [comment]
@dev-aravind Thanks.  Here is some feedback:

 Example event [Paul Mirabel](https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Fevenko.ca%2Fevent%2Fe001848) 
- [ ] the property schema:performers is deprecated and should be schema:performer (without 's')
- [ ] the performer's object is type schema:performer which is not a type. Please use type PerformingGroup for all since I don't think you can tell if the performer is a Person or Organization.
- [ ]  Please add schema:copyRight to all ImageObjects with the texts in both en and fr. See the main description of this issue at the top.

**Comment by dev-aravind** [comment]
@saumier The issues are now fixed except the special_guest performer one, I tried a method using the schema.org documentation but not sure if this is the right way. Please test [this](https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20evenko-ca&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-evenko/evenko-ca) and let me know.

**Comment by saumier** [comment]
@dev-aravind 

The way you used schema:Role is perfect. The SHACL needs adjustment but otherwise there are no changes needed.

Here are a few things to fix:
- [ ] The schema.org property for keyword is actually `schema:keywords`. I misled you. Sorry. Please adjust the mapping.
- [ ] In events with multiple keywords please separate. For example [ZZTop](https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Fevenko.ca%2Fevent%2Fe004104) has `eventid1 schema:keywords "Blues,Rock"` but it should be `'eventid1 schema:keywords "Blues" . eventid1 schema:keywords "Rock" .`

**Comment by dev-aravind** [comment]
@saumier These are now fixed. Please check the same event mentioned in the previous event to test.
