### ISSUE TITLE
CSRF - ETL scenesfrancophones.ca

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#11]
This project is to scrape the JSON-LD from the following lists on the website scenesfrancophones.ca:
1. https://scenesfrancophones.ca/diffuseurs (about 131 organizations)
2. https://scenesfrancophones.ca/artistes (about 181 artists)
3. https://scenesfrancophones.ca/spectacles (about 56 events)

The data should be saved in individual files (one for each listing) in JSON-LD in a Github repository called artsdata-planet-scenesfrancophones-ca.

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-planet-scenesfrancophones/issues/6
- [ ] https://github.com/culturecreates/artsdata-planet-scenesfrancophones/issues/7
- [ ] https://github.com/culturecreates/artsdata-planet-scenesfrancophones/issues/8
```
