### ISSUE TITLE
List of Huginn ports to Ruby

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#18]
List of web sites JSON-LD to send to the Artsdata Databus

Including but not limited to:
- [ ] Capitol theatre https://huginn-staging.herokuapp.com/scenarios/7
- [ ] Yardbird https://huginn-staging.herokuapp.com/scenarios/9
- [ ] Japanese Canadian Artists - https://huginn-staging.herokuapp.com/scenarios/10
- [ ] Le Vivier - https://huginn-staging.herokuapp.com/scenarios/24
- [ ] Reservatech - https://huginn-staging.herokuapp.com/scenarios/11
- [ ] ScenePro https://huginn-staging.herokuapp.com/scenarios/21
- [ ] Totem -  https://huginn-staging.herokuapp.com/scenarios/25

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/nebula/issues/5
- [ ] https://github.com/culturecreates/artsdata-planet-nac/issues/2
```
