### ISSUE TITLE
2324-W-001 Scène Pro batch upload to Wikidata

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#2]
2324-W-001

https://docs.google.com/document/d/1kqI7WytMVgOiDaU67ymVc6kWuVcbCKyS3EcdvZXe7MM/edit

Scène Pro batch upload to Wikidata

- ETL venues and organizations to Wikidata using the same schemas as in 2022 (link)
- Compare the 2022 organization dataset to the 2023 dataset. Do this using  "member of Rideau" (https://www.wikidata.org/wiki/Property:P463 https://www.wikidata.org/wiki/Q87727957) and check the retrieved year.  If organizations are missing in 2023, this may mean they no longer are members. If that’s the case, provide a list to CAPACOA. 
- Mint Artsdata IDs for ScenePro Organizations and Venues if missing and pass Artsdata SHACL.
- Provide a short editgroups.toolforge.org report [example from 2022](https://editgroups.toolforge.org/?user=Caitlin+Troughton), including number of items created/edited and list of items that failed to upload.
- Provide a CSV with item name, Scene Pro ID, Artsdata ID and Wikidata ID.

Note:CAPACOA has been manually populating Scène Pro venues that have the same address ([see this spreadsheet](https://docs.google.com/spreadsheets/d/1QFZKjSJDHP-sj1FWe56wNJ6FdrLyDPZWDSXoa4iw97g/edit#gid=178964688)). The resulting items and the newly created building items should be minted an Artsdata ID.

Work should be complete by January 31st.

Report
https://docs.google.com/document/d/1xwhEU5FL78pcArCXQqYYl84oxfB4ouo-ihHoiTKuOXk/edit#heading=h.q8u8ocado0fn

```[tasklist]
### Tasks
- [x] Review additional steps in work order by Fred
- [x] list members that have ended membership from Artsdata view point
- [x] Mint new Organization entities in Artsdata
- [x] Openrefine: Update all organizations from inital upload “latest start date (P8555)”: “2022-04-10”
- [x] Openrefine: Upload/reconcile organizations to Wikidata - pass 1 without venue link,  retrieved (P813) date updated
- [x] OpenRefine: For new members add “latest start date (P8555)”: “<Date of the data extraction>”;
- [x] Openrefine: Update terminated members: “Latest end date (PXXXX)”: “<Date of the data extraction (or a more accurate date of the database manager can provide one)>; The main “member of” statement should be deprecated; The following qualifier statement should be added: "reason for deprecated rank" (P2241): “obsolete (Q107356532)”; In the reference, the “retrieved (P813)” date should be updated to correspond to the date when the current dataset was extracted for upload.
- [x] Mint new Place entities in Artsdata
- [x] OpenRefine: Create new/reconcile venues
- [x] OpenRefine: Add to Organizations the venue relationship
```

**Comment by saumier** [comment]
Using [Saumier@artsdata-gregory-bot](https://www.wikidata.org/wiki/User:Saumier@artsdata-gregory-bot)

**Comment by saumier** [comment]
Edit groups https://editgroups.toolforge.org/?user=Saumier



![Image](https://github.com/culturecreates/artsdata-orion/assets/419491/6a0c8ae6-5c94-441b-ab64-59b9492bc445)


https://editgroups.toolforge.org/b/OR/fe0b53ca35c/
https://editgroups.toolforge.org/b/OR/c56cdc02521/
https://editgroups.toolforge.org/b/OR/313428b1356/
https://editgroups.toolforge.org/b/OR/d6774ab78d2/

**Comment by saumier** [comment]
Creating new venues from ScenePro 

https://editgroups.toolforge.org/b/OR/9d3280574aa/   - 18 new
https://editgroups.toolforge.org/b/OR/6f89acb3f36/  - 7 new
https://editgroups.toolforge.org/b/OR/51eb858f8be/  - 2 new
https://editgroups.toolforge.org/b/OR/ae82ccb963a/  - 1 new
https://editgroups.toolforge.org/b/OR/f1bdf1cae21/  - 48 new

**Comment by saumier** [comment]
linking organizations to venues for ScenePro via Artsdata.ca

https://editgroups.toolforge.org/b/OR/83a912f28ab/ - 109 edits
