### ISSUE TITLE
2324-W-003 ATC

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#34]
[Work order](https://docs.google.com/document/d/19wpHr0xN9LEg9E4TASPGWEDXgrcKRu3lriScBDxS0MM/edit#heading=h.phzh70cof3ne)

2024 meeting with Northern
https://docs.google.com/document/d/1eODpucMG3XKuHcfHfE7mjT43oA--BU6U-JsRtLjzhbs/edit

```[tasklist]
### Tasks 2023
- [x] Phase 1: Support Reconciliation by ATC
- [ ] Phase 2: Mint new URIs in Artsdata
- [ ] Phase 3: Reconcile and mint new URIs in Wikidata
- [ ] Phase 4: Deliver Artsdata URIs back to ATC
```
