### ISSUE TITLE
2425-W-006 iCal Output Implementation

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#47]
Work Order: https://docs.google.com/document/d/1hQ7l2VsBc5uuk_n_bTyiavMe2mU-bSCOuXxU6GCSLhU/edit

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-orion/issues/48
- [x] Setup ICal test server (Word Press + iCal ShortCode)
- [x] Meet with Gary to plan event data
- [x] Button for Gary to upload spreadsheet by himself
- [ ] https://github.com/culturecreates/artsdata-ical/issues/1
- [x] https://github.com/culturecreates/artsdata-ical/issues/2
- [x] Pilot Support (September)
- [ ] https://github.com/culturecreates/artsdata-ical/issues/11
- [ ] https://github.com/culturecreates/artsdata-ical/issues/12
```

**Comment by saumier** [comment]
Gregory to ask Gary to send iCal url to Gary for installation on CAPACOA test site using a simple plugin called: iCal ShortCode

**Comment by saumier** [comment]
@fjjulien I have added documentation in english and french, and I added another iCal feed with all upcoming events from complexeculturelfelixleclerc.com.

I am closing this WO. Let me know if you see anything missing.

**Comment by fjjulien** [comment]
@saumier I would like the documentation to be also available within the Artsdata infrastructure section, because that is where developers will look for it. 

I created this page: https://github.com/culturecreates/artsdata-data-model/edit/master/_architecture/ical.md

Notes: 

- I wasn't able to retrieve the proper markdown for the list of requirements. I'll let you add it.
- I would like us to include a sample server response once we are done implement Date-Time Form 3. Please create a task in the TZID work order, so that we don't forget to edit this page.

**Comment by fjjulien** [comment]
@saumier Did you resolve the UID issue yet? Until the iCal server can deliver persistent, globally UIDs, other users may have the same problem as CAPACOA.

**Comment by saumier** [comment]
@fjjulien yes. The IDs in the iCAL feed are persistent. This was fixed about 2 weeks ago, the day after you mentioned it.

**Comment by saumier** [comment]
> I wasn't able to retrieve the proper markdown for the list of requirements. I'll let you add it.
Done.  https://github.com/culturecreates/artsdata-data-model/edit/master/_architecture/ical.md

> I would like us to include a sample server response once we are done implement Date-Time Form 3. Please create a task in the TZID work order, so that we don't forget to edit this page.

https://github.com/culturecreates/artsdata-orion/issues/121
