### ISSUE TITLE
2425-W-005 OSAC Event Data ETL

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#55]
WO reference https://docs.google.com/document/d/1krRWkKYVh8woshxsS66bk5tFSyNsetIygu91PCVXtGA/edit#heading=h.phzh70cof3ne

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-planet-osac/issues/4
- [ ] https://github.com/culturecreates/artsdata-planet-osac/issues/1
- [ ] https://github.com/culturecreates/artsdata-planet-osac/issues/3
- [ ] https://github.com/culturecreates/artsdata-orion/issues/89
```

**Comment by saumier** [comment]
@saumier Ask Skip to try and convert address strings into things.

**Comment by saumier** [comment]
@fjjulien This WO is completed.

**Comment by saumier** [comment]
@tammy-culture This WO is complete. Please send final invoice if not already done. Thx.

**Comment by tammy-culture** [comment]
@saumier Done
