### ISSUE TITLE
2425-W-011 TicketPro

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#75]
Reference doc: https://docs.google.com/document/d/1qwKOluB-vkCihOa5h4AtQVnhq8SwDpYtx-9r0MPW_mw/edit#heading=h.phzh70cof3ne

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-orion/issues/76
- [ ] https://github.com/culturecreates/artsdata-orion/issues/84
- [ ] https://github.com/culturecreates/artsdata-orion/issues/92
- [ ] Reconcile and mint events
- [x] Report
```

**Comment by saumier** [comment]
@fjjulien We have completed a first pass at loading all events from TicketPro. There are 592 events from TicketPro across 3 data feeds. However, the times for the events are wrong because the wrong time zone is used.  For example: https://tpromaclab.ticketpro.ca/en/pages/Maclab_AJE has the wrong time zone as seen with validator.schema.org.

I propose we open a new WO to address the time zone issue once and for all as a service in Artsdata as we have discussed many times in the past.  This is becoming critical. Lets discuss.

**Comment by fjjulien** [comment]
@saumier I agree. Here is a [new work order dedicated to time zone matter](https://docs.google.com/document/d/1s2PKX-V1Gn2C-mUzGY4Hf5E95p0a4lnKJpDVXg-yMuE/edit?usp=sharing).

As to Ticketpro's specific errors, please have a look at the data and try to detect recurring error patterns and report your findings. I will then notify Ticketpro.

**Comment by saumier** [comment]
@fjjulien The 3 sources for Ticketpro are loading and look very good apart from the time zone. 

This event "Therrien-Go Duo" has a score of 83% [Iink to score](https://kg.artsdata.ca/en/dereference/external?post_sparql=https%3A%2F%2Fraw.githubusercontent.com%2Fculturecreates%2Fartsdata-score%2Fmain%2Fsparql%2Fscore_algorithm.sparql&shacl=https%3A%2F%2Fraw.githubusercontent.com%2Fculturecreates%2Fartsdata-score%2Fmain%2Fshacl%2Fshacl_for_scoring.ttl&uri=https%3A%2F%2Fww3.ticketpro.ca%2Fevent.php%3Fevent_id%3D10142)

There are about 620 events without errors across the 3 regions. Only about 40 events with validation errors mostly because of missing startTime (and most are not really events but rather a gift tickets or passes).

Feedback to improve their JSON-LD:
1.  In a few events the schema:Performer has a error because of a missing @type.
SYLVAIN COSSETTE.  I sometimes see @Thing which is one of the suggestions you made and is better than having the wrong type. My suggestion is to use @PerformingGroup because a group can be made of 1 person and is still a sub-type of Organization but more clear that the person is performing. 
2. In a few events the schema:Location is empty but should be present. https://spectart.com/programmation/back-to-the-80s-band/
3. Many events from Ticketpro are missing JSON-LD completely.
Example: https://ww3.ticketpro.ca/event.php?event_id=10142

**Comment by fjjulien** [comment]
@saumier Here is a draft project report derived from the above comments: https://docs.google.com/document/d/1aOCsaKCAUp1y3H2ZwNM8Tdr1jMiJXr8fBpwH9wQwGr0/edit?usp=sharing

Please review, complete, and sign off to close the project.

**Comment by saumier** [comment]
@fjjulien I reviewed the project report and it looks good. Thank you very much.
