### ISSUE TITLE
2425-W-012 ATC Integration

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#85]
WO Doc https://docs.google.com/document/d/1NxVpk2kp4cYhVQs20V6tAQOlO16b75pxmOD9ZVwFI7o/edit#heading=h.phzh70cof3ne
```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-api/issues/17
- [ ] https://github.com/culturecreates/artsdata-planet-atc/issues/1
- [x] Create new Frame for Artsdata Search Query
- [ ] Add techArticleUrl to Frame
- [ ] https://github.com/culturecreates/artsdata-planet-atc/issues/5
```

**Comment by saumier** [comment]
SPARQL tests to get Wikipedia URI from Wikidata
```
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX schema: <http://schema.org/>
PREFIX dbo: <http://dbpedia.org/ontology/>

PREFIX adm: <http://kg.artsdata.ca/minted/>
insert {
    graph adm:K2 {
        ?ad_uri schema:sameAs ?article .
    }    
}
where {
    service <https://query.wikidata.org/sparql> {
        ?a wdt:P7627 ?adid .
        ?article schema:about ?a .
        ?article schema:isPartOf <https://fr.wikipedia.org/>.
    }
    bind(URI(CONCAT("http://kg.artsdata.ca/resource/",?adid)) as ?ad_uri)
}
```

**Comment by saumier** [comment]
SPARQL tests to add DBpedia English bio to Artsdata core

```
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX prov: <http://www.w3.org/ns/prov#>


insert {
    graph <http://kg.artsdata.ca/core> {
        << ?person schema:description ?c_en >>  prov:wasDerivedFrom  [  
                   prov:wasDerivedFrom ?sameAs ;
                   prov:hadPrimarySource <http://kg.artsdata.ca/resource/K1-18> ;
                   prov:generatedAtTime ?stamp ] .
    }
}
where {
    bind (now() as ?stamp )
    {
        select  ?person ?sameAs_http ?sameAs where {
            ?person a schema:Organization .
            filter(contains(str(?person),"kg.artsdata.ca/resource"))
            ?person schema:sameAs ?sameAs .
            filter(contains(str(?sameAs),"en.wikipedia.org"))
            bind(uri(concat("http:", strafter(str(?sameAs),"https:"))) as ?sameAs_http)
        } 
    }
    service <https://dbpedia.org/sparql> {
        ?sameAs_http foaf:primaryTopic ?a .
        ?a dbo:abstract ?c .
        filter(lang(?c) = "en")
       
    } 
     bind(strlang(?c,"en") as ?c_en)
    filter(bound(?c_en))
}
```

**Comment by saumier** [comment]
Test SPARQL to add workLocation from Wikidata P937 to Artsdata core

```
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX schema: <http://schema.org/>
insert {
    graph <http://kg.artsdata.ca/core> {
        ?ad_uri  schema:workLocation [ 
            a schema:Place ;
            schema:address [ 
            	a schema:PostalAddress ;
                schema:addressCountry "CA" ;
                schema:addressRegion ?prov_code  ] 
        ]
    }
}
where {
    service <https://query.wikidata.org/sparql> {
        ?a wdt:P7627 ?adid .
        ?a wdt:P31 wd:Q5 ;
           wdt:P937 ?worklocation .
        ?worklocation wdt:P131* ?prov .
        ?prov wdt:P31 wd:Q11828004 .
        ?prov wdt:P300 ?code
    }
    bind(strafter(?code,"-") as ?prov_code )
    bind(URI(concat("http://kg.artsdata.ca/resource/",?adid)) as ?ad_uri)
}
```

**Comment by saumier** [comment]
Test SPARQL to get Max capacity from Wikidata

```
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX schema: <http://schema.org/>
insert {
    graph <http://kg.artsdata.ca/core> {
        ?ad_uri  schema:workLocation [ 
            a schema:Place ;
            schema:address [ 
            	a schema:PostalAddress ;
                schema:addressCountry "CA" ;
                schema:addressRegion ?prov_code  ] 
        ]
    }
}
where {
    service <https://query.wikidata.org/sparql> {
        ?a wdt:P7627 ?adid .
        ?a wdt:P31 wd:Q5 ;
           wdt:P937 ?worklocation .
        ?worklocation wdt:P131* ?prov .
        ?prov wdt:P31 wd:Q11828004 .
        ?prov wdt:P300 ?code
    }
    bind(strafter(?code,"-") as ?prov_code )
    bind(URI(concat("http://kg.artsdata.ca/resource/",?adid)) as ?ad_uri)
}
```

**Comment by saumier** [comment]
Test SPARQL to add workLocation from IWTS

```
PREFIX schema: <http://schema.org/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX prov: <http://www.w3.org/ns/prov#>
insert {
    graph <http://kg.artsdata.ca/core> {
        ?adid  schema:workLocation  ?workLocation .
        <<  ?adid  schema:workLocation  ?workLocation >> prov:wasDerivedFrom    <http://kg.artsdata.ca/databus/culture-creates/artsdata-planet-iwts/iwts-ca/2025-02-05T05_37_04#DataId> .
        ?workLocation schema:address [ 
            a schema:PostalCode ;
            schema:addressCountry ?country ;
            schema:addressRegion ?region 
        ]
    }
}
where {
    graph <http://kg.artsdata.ca/culture-creates/artsdata-planet-iwts/iwts-ca> {
        ?person a schema:Person .
        ?person schema:workLocation ?loc .
        ?loc schema:address/schema:addressCountry ?country.
        ?loc schema:address/schema:addressRegion ?region .
    }
    ?person  schema:sameAs ?adid .
    filter(contains(str(?adid),"kg.artsdata.ca"))
    bind(URI(CONCAT(str(?adid),"#workLocation")) as ?workLocation )
    filter(not exists {
            ?adid schema:workLocation ?some_loc
        })
}
```
