### ISSUE TITLE
CAPACOA Work Orders 2425

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-orion#9]
Master Sheet https://docs.google.com/spreadsheets/d/1AfVcgcoKjjR2krzuld5WFBYv1vqoUy2jLMq8bPrI0TY/edit?gid=0#gid=0

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-orion/issues/38
- [ ] https://github.com/culturecreates/artsdata-google-workspace-smart-chip/issues/3
- [ ] https://github.com/culturecreates/artsdata-orion/issues/43
- [ ] https://github.com/culturecreates/artsdata-planet-iwts/issues/1
- [ ] https://github.com/culturecreates/artsdata-orion/issues/55
- [ ] https://github.com/culturecreates/artsdata-orion/issues/47
- [ ] https://github.com/culturecreates/nebula/issues/27
- [ ] https://github.com/culturecreates/artsdata-planet-lavitrine/issues/44
- [ ] https://github.com/culturecreates/artsdata-planet-lavitrine/issues/40
- [ ] https://github.com/culturecreates/artsdata-score/issues/7
- [ ] https://github.com/culturecreates/artsdata-orion/issues/75
- [ ] https://github.com/culturecreates/artsdata-orion/issues/85
- [ ] https://github.com/culturecreates/artsdata-orion/issues/95
- [ ] https://github.com/culturecreates/artsdata-orion/issues/96
- [ ] https://github.com/culturecreates/artsdata-planet-ipaa/issues/8
- [ ] https://github.com/culturecreates/artsdata-orion/issues/98
- [ ] https://github.com/culturecreates/artsdata-orion/issues/115
- [ ] https://github.com/culturecreates/artsdata-orion/issues/116
- [ ] https://github.com/culturecreates/artsdata-orion/issues/114
- [ ] https://github.com/culturecreates/artsdata-orion/issues/120
- [ ] https://github.com/culturecreates/artsdata-orion/issues/124
- [ ] https://github.com/culturecreates/artsdata-orion/issues/123
```
